### ISSUE TITLE
Is it possible to use the component with SSR?

### ISSUE THREAD

**Issue by KleinMaximus** [egoist/vue-media#3]

**Comment by egoist** [comment]
It works on server side, the component is hidden by default unless you set prop `visiblewByDefault` to true

**Comment by KleinMaximus** [comment]
Thanks! I asked not looking carefully code. Now I get it.

**Comment by equinusocio** [comment]
Using this component as-is with nuxt and ssr i get an error:
`document is not defined`

**Comment by egoist** [comment]
@equinusocio maybe your code used `document`? `visibleByDefault` is just a prop which is the default value of the state `matches`:  https://github.com/egoist/vue-media/blob/708dd49f52d8c6721e6d8a0156814e886a9e44b3/src/index.js#L5-L19

**Comment by equinusocio** [comment]
@egoist Yes thank you, i was using `document`. BTW, i think that `visibleByDefault ` should be mentioned somewhere in the readme.

**Comment by egoist** [comment]
@equinusocio yup added here: https://github.com/egoist/vue-media/blob/master/README.md#props

**Comment by equinusocio** [comment]
Nice!
